### PR TITLE
Close stdin before calling the callback

### PR DESCRIPTION
**Pull request by gnuletik**
Hi !

Here is a small change to avoid node to hang before exiting.

Let me know if you have any questions :)

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 process just hangs open without this

http://stackoverflow.com/questions/26004519/why-doesnt-my-node-js-process-terminate-once-all-listeners-have-been-removed

~~missing line end in this pr~~

**Comment by gnuletik** [comment]
Oh yes, I forgot the `;`. This is fixed :)

**Comment by oliverfoster** [comment]
awesome \* highfives \* :D

**Comment by gnuletik** [comment]
Hi @tcql, any news on this ?

**Comment by RamIdeas** [comment]
`npm install tcql/node-yesno#1/head` or `yarn add tcql/node-yesno#1/head` until this gets merged

**Comment by mreinstein** [comment]
@tcql has graciously accepted my request to help with maintainership. Ready and waiting for PRs/issues/etc.!

**Comment by mreinstein** [comment]
published to npm as 0.1.0

**Comment by andrewzolotukhin** [comment]
Hi @mreinstein , this causes an issue:

```js
let yesno = require('yesno');

const yes_values = ['Y'], no_values = ['N'];

yesno.ask('first?', 'Y', val => {
	console.log(val);
	yesno.ask('second?', 'Y', val => {
		console.log(val);
	}, yes_values, no_values);
}, yes_values, no_values);
```


it asks only one time the second question is only printed. It was working before and was caused by this merge request.

**Pull request merged**
