### PR TITLE
add uppercase support (fix issue tcql#10)

### PR DESCRIPTION
**Pull request by Creative-Difficulty**

### CODE REVIEW

**Comment by mreinstein** [comment]
Thanks for the PR!

I've fixed this via https://github.com/tcql/node-yesno/commit/c7d5f7c33ef084ee094b204f9d1d1f37336c1d9b instead, because the library is intentionally case insensitive.

**Comment by Creative-Difficulty** [comment]
No you didn't!!

**Comment by mreinstein** [comment]
Please be more specific.  As far as I can tell the issue is resolved. My test case:

```javascript
   const version = '1.5.5'

   const r = await yesno({
       question: `Version will be ${version}, continue?? (y/n)?`,
       noValues: ["no", "NO", "No", "n", "N"],
       yesValues: ["yes", "YES", "Yes", "y", "Y"],
   })

   console.log('r:', r)
```

produces:

```bash
Version will be 1.5.5, continue?? (y/n)? BLARGH

Invalid Response.
Answer either yes : (yes, YES, Yes, y, Y)
Or no: (no, NO, No, n, N)

Version will be 1.5.5, continue?? (y/n)? Y
r: true
```

**Comment by Creative-Difficulty** [comment]
Yeah, but there's still the `.toLowerCase()` in parsing so your fix is only cosmetic and therefore useless!!

**Comment by mreinstein** [comment]
Yo, be constructive. I'm trying to help you with your issue in this open source, free module.

I just provided a code snippet and output, based on v0.4.0. As far as I can tell the issue is resolved.

If it is truly not resolved, please share your code that isn't working with node-yesno@0.4.0 and we'll work through it.

**Pull request closed without merging**
